### ISSUE TITLE
Precision grab and follow rigidbody leads to erratic rotations

### ISSUE THREAD

**Issue by SmartCarrion** [ExtendRealityLtd/Tilia.Interactions.Interactables.Unity#58] opened 2020-11-18 08:22 UTC
### Environment

* Code source: package manager
* Code version: 1.14.1
* Platform version: Unity 2019.4.14f1
* 3rd party dependencies: none

### Steps to reproduce

Create a basic Tilia test project.  Make a long interactable like a bat.  Set it to **follow rigidbody** and **precision grab**.  
Grab the bat at one end and flip your hand over repeatedly, like you are looking at your palm and the back of your hand.

### Expected behavior

The bat moves smoothly like a real world object

### Current behavior

The bat occasionally enters some kind of gimbal lock and start flipping out wildly in all directions.

**Comment by SmartCarrion** [comment] 2020-11-18 08:23
Maybe the rotation is being lerped using Euler angles instead of quaternions somewhere?

**Comment by SmartCarrion** [comment] 2020-11-18 08:40
actually it seems to be a result of moving the center of the gameobject (rigidbody position), and that travelling a long distance with rotation.  Maybe if we dynamically offset the rigidbody center to be at the hand, it would move smoother.

**Comment by HugoCortell** [comment] 2020-11-22 05:28
Hold on, is [this](https://cdn.discordapp.com/attachments/717121338409484319/779939623145046056/vlc-record-2020-11-22-06h20m59s-2020-11-22_06-16-47.mkv-.mp4) the same issue you are having?

**Comment by HugoCortell** [comment] 2020-11-24 05:15
During a playtest I found this error:
```cs
            if (!angle.ApproxEquals(0))
            {
                Vector3 angularTarget = angle * axis;
                Vector3 calculatedAngularVelocity = Vector3.MoveTowards(cachedTargetRigidbody.angularVelocity, angularTarget, MaxDistanceDelta);
                if (float.IsPositiveInfinity(AngularVelocityLimit) || calculatedAngularVelocity.sqrMagnitude < AngularVelocityLimit)
                {
                    cachedTargetRigidbody.angularVelocity = calculatedAngularVelocity;
                }
            }
```
```
rigidbody.angularVelocity assign attempt for 'InfectionCube' is not valid. Input angularVelocity is { NaN, NaN, NaN }.
UnityEngine.Rigidbody:set_angularVelocity(Vector3)
Zinnia.Tracking.Follow.Modifier.Property.Rotation.RigidbodyAngularVelocity:DoModify(GameObject, GameObject, GameObject) (at Library/PackageCache/io.extendreality.zinnia.unity@1.25.1/Runtime/Tracking/Follow/Modifier/Property/Rotation/RigidbodyAngularVelocity.cs:59)
Zinnia.Tracking.Follow.Modifier.Property.PropertyModifier:Modify(GameObject, GameObject, GameObject) (at Library/PackageCache/io.extendreality.zinnia.unity@1.25.1/Runtime/Tracking/Follow/Modifier/Property/PropertyModifier.cs:68)
Zinnia.Tracking.Follow.Modifier.FollowModifier:Modify(GameObject, GameObject, GameObject) (at Library/PackageCache/io.extendreality.zinnia.unity@1.25.1/Runtime/Tracking/Follow/Modifier/FollowModifier.cs:95)
Zinnia.Tracking.Follow.ObjectFollower:ApplySourceToTarget(GameObject, GameObject) (at Library/PackageCache/io.extendreality.zinnia.unity@1.25.1/Runtime/Tracking/Follow/ObjectFollower.cs:115)
Zinnia.Process.Component.SourceTargetProcessor`3:ApplySourcesToTargets(HeapAllocationFreeReadOnlyList`1, HeapAllocationFreeReadOnlyList`1) (at Library/PackageCache/io.extendreality.zinnia.unity@1.25.1/Runtime/Process/Component/SourceTargetProcessor.cs:101)
Zinnia.Process.Component.GameObjectSourceTargetProcessor:Process() (at Library/PackageCache/io.extendreality.zinnia.unity@1.25.1/Runtime/Process/Component/GameObjectSourceTargetProcessor.cs:56)
Zinnia.Tracking.Follow.ObjectFollower:Process() (at Library/PackageCache/io.extendreality.zinnia.unity@1.25.1/Runtime/Tracking/Follow/ObjectFollower.cs:99)
Zinnia.Process.Moment.MomentProcess:ProcessNow() (at Library/PackageCache/io.extendreality.zinnia.unity@1.25.1/Runtime/Process/Moment/MomentProcess.cs:58)
Zinnia.Process.Moment.MomentProcess:Process() (at Library/PackageCache/io.extendreality.zinnia.unity@1.25.1/Runtime/Process/Moment/MomentProcess.cs:44)
Zinnia.Process.Moment.MomentProcessor:Process() (at Library/PackageCache/io.extendreality.zinnia.unity@1.25.1/Runtime/Process/Moment/MomentProcessor.cs:199)
Zinnia.Process.Moment.MomentProcessor:FixedUpdate() (at Library/PackageCache/io.extendreality.zinnia.unity@1.25.1/Runtime/Process/Moment/MomentProcessor.cs:87)
```

However, this was under very strange circumstances, I had attempted to backtrack to 1.13.4 (although clearly, it did not work) and this error has not appeared since.

**Comment by thestonefox** [comment] 2020-11-25 10:33
Version 14.1 introduced changes in Zinnia, specifically this:

```
The RigidbodyAngularVelocity component was calculating the angle of angular velocity in degrees but angular velocity is set in radians so this was causing artifacts when rotating.

The fix is to ensure the angle is calculated in radians.
```

Commit: https://github.com/ExtendRealityLtd/Zinnia.Unity/commit/446974ebf855caf0de9bd3407e8ea94ffe838a73

For issue: https://github.com/ExtendRealityLtd/Zinnia.Unity/issues/518

I'd recommend you try changing the code back in zinnia and seeing if it fixes this issue and report any findings.

**Comment by HugoCortell** [comment] 2020-11-25 11:37
> 
> 
> Version 14.1 introduced changes in Zinnia, specifically this:
> 
> ```
> The RigidbodyAngularVelocity component was calculating the angle of angular velocity in degrees but angular velocity is set in radians so this was causing artifacts when rotating.
> 
> The fix is to ensure the angle is calculated in radians.
> ```
> 
> Commit: [ExtendRealityLtd/Zinnia.Unity@446974e](https://github.com/ExtendRealityLtd/Zinnia.Unity/commit/446974ebf855caf0de9bd3407e8ea94ffe838a73)
> 
> For issue: [ExtendRealityLtd/Zinnia.Unity#518](https://github.com/ExtendRealityLtd/Zinnia.Unity/issues/518)
> 
> I'd recommend you try changing the code back in zinnia and seeing if it fixes this issue and report any findings.

_**Yep!**_ I just tried it out on both a new VRTK project and my game and it seems to work perfectly!
Thank you fox! Really, thank you.

**Comment by thestonefox** [comment] 2020-11-25 11:39
So it would seem that change in zinnia is causing a break here then.

**Comment by thestonefox** [comment] 2020-12-07 13:25
This issue is being caused by this fundamental issue: https://github.com/ExtendRealityLtd/Zinnia.Unity/issues/518

**Comment by thestonefox** [comment] 2020-12-13 00:04
Fixed in latest version

**Closed by thestonefox** 2020-12-13 00:04 UTC
Labels: bug

**Comment by SmartCarrion** [comment] 2020-12-13 05:57
Really?  Can't wait to try it.  I just found that adding in
            if (angle > 180)  //from newtonVR
                angle -= 360;
at line 51 of RigibodyAngularVelocity.cs was a HUGE help in the old version.  I'll pull the new code and test.

**Comment by SmartCarrion** [comment] 2020-12-13 06:14
Wow, way better.  I can't belive we both worked on this the same day.  I bet your fix was a lot of work, thank you!!!
