### ISSUE TITLE
After instantiating an interactable, error if called interactor.Grab() immediately

### ISSUE THREAD

**Issue by fight4dream** [ExtendRealityLtd/Tilia.Interactions.Interactables.Unity#36] opened 2020-07-16 10:43 UTC
### Environment

* Code source: https://github.com/ExtendRealityLtd/Tilia.Interactions.Interactables.Unity/
* Code version: 1.11.1
* Platform version: Unity 2019.4.1f1
* 3rd party dependencies:

### Steps to reproduce

1. add an interactor
2. create a cube
3. use tilia interactable creator to turn this cube into an interactable
4. drag the interactable into project tab to create an original prefab
5. use the following script (to spawn the interactable prefab at runtime)
6. link the spawner's Spawned event to interactor.Grab(GameObject)

```
public class Spawner : MonoBehaviour
{
    public GameObject Prefab;

    [Serializable]
    public class GameObjectUnityEvent : UnityEvent<GameObject> { }
    public GameObjectUnityEvent Spawned;

    [ContextMenu("Spawn")]
    public void Do()
    {
        GameObject go = Instantiate(Prefab, t.position, t.rotation);
        if (go)
        {
            Spawned?.Invoke(go);
        }
    }
}
```

### Expected behavior

the instantiated interactable is grabbed by the interactor

### Current behavior

an error occurred.
[message.txt](https://github.com/ExtendRealityLtd/Tilia.Interactions.Interactables.Unity/files/4930929/message.txt)

### Side note

it can be grabbed with no error if delayed to end of frame.
for example:
```
    [ContextMenu("Spawn")]
    public void Do()
    {
        GameObject go = Instantiate(Prefab, t.position, t.rotation);
        if (go)
        {
            StartCoroutine(RaiseSpawned(go));
        }
    }

    private IEnumerator RaiseSpawned(GameObject go)
    {
        yield return new WaitForEndOfFrame();
        Spawned?.Invoke(go);
    }
```

**Comment by thestonefox** [comment] 2020-07-16 10:46
There is already a GrabAtEndOfFrame method, can't you just use that?

**Comment by fight4dream** [comment] 2020-07-16 10:47
i can't find it on interactor
![image](https://user-images.githubusercontent.com/22952143/87662466-d2909780-c794-11ea-8a50-89e8aec63b9c.png)

**Comment by thestonefox** [comment] 2020-07-16 10:50
oh it's on the interactable.

I think things like this probably do need waiting for the set up to finish. But I'll investigate this further to see if there's an actual issue or whether the solution _is_ to do it at the end of the frame.

**Comment by fight4dream** [comment] 2020-07-16 10:55
![image](https://user-images.githubusercontent.com/22952143/87662980-ad505900-c795-11ea-9328-336776da93de.png)
supplementary image to show the desired event call 
so this suggest the counter part API interactor.GrabAtEndOfFrame(interactable)

**Comment by thestonefox** [comment] 2020-08-09 16:05
This error is caused by:

`GrabInteractableConfigurator.cs` in the `ConfigureActionContainer` method (line 241)

It attempts to set up the `action.GrabSetup` when the action is enabled. But due to how Unity is enabling the prefab in a random order then that action is not quite set up at the point the grab logic occurs, which doesn't make much sense as you'd think Unity would finish instantiating and enabling the prefab before invoking the event.

Anyway a quick fix in code is to force set the `action.GrabSetup` and then wait for the component to become enabled still (so any additional set up also occurs)

i.e.

```
protected virtual void ConfigureActionContainer(GrabInteractableAction action)
{
    if (action == null)
    {
        return;
    }

    action.GrabSetup = this;
    action.RunWhenActiveAndEnabled(() => action.GrabSetup = this);
}
```

I'll raise a PR with this 1 line fix.

**Comment by extendreality** [comment] 2020-08-13 12:25
Fixed with https://github.com/ExtendRealityLtd/Tilia.Interactions.Interactables.Unity/pull/48

**Closed** 2020-08-14 13:54 UTC
Labels: bug
